# Generated by Django 6.0.4 on 2026-04-10 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notespage',
            options={'ordering': ['order']},
        ),
    ]
