# Generated by Django 6.0.4 on 2026-04-10 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_notespage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='practiceset',
            name='numbas_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='unittest',
            name='numbas_url',
            field=models.URLField(blank=True),
        ),
    ]
