# Generated by Django 6.0.4 on 2026-04-10 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_courseaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalexam',
            name='numbas_url',
            field=models.URLField(blank=True),
        ),
    ]
