# Generated by Django 6.0.4 on 2026-04-10 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_finalexam_numbas_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='duration',
            field=models.CharField(blank=True, help_text='e.g. 12:34', max_length=20),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='lessons/thumbnails/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='transcript',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_file',
            field=models.FileField(blank=True, upload_to='lessons/videos/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, help_text='Paste an embed URL, e.g. https://www.youtube.com/embed/VIDEO_ID'),
        ),
    ]
