# Generated by Django 6.0.4 on 2026-04-10 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_lesson_duration_lesson_is_published_lesson_thumbnail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.PositiveIntegerField(help_text='Time in seconds when the video pauses. e.g. 90 = 1:30')),
                ('question', models.TextField(help_text='The question shown to the student at this timestamp.')),
                ('order', models.IntegerField(default=0)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='catalog.lesson')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CheckpointChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('checkpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='catalog.videocheckpoint')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
