# Generated by Django 6.0.4 on 2026-04-10 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_checkpointresponse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseAccess',
        ),
    ]
