# Generated by Django 6.0.4 on 2026-04-13 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_delete_courseaccess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalexam',
            name='numbas_url',
        ),
        migrations.RemoveField(
            model_name='practiceset',
            name='numbas_url',
        ),
        migrations.RemoveField(
            model_name='unittest',
            name='numbas_url',
        ),
    ]
