# Generated by Django 6.0.4 on 2026-04-13 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_sitesettings_alter_unit_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='background_position',
            field=models.CharField(choices=[('center', 'Center'), ('top center', 'Top center'), ('bottom center', 'Bottom center'), ('top left', 'Top left'), ('top right', 'Top right'), ('bottom left', 'Bottom left'), ('bottom right', 'Bottom right')], default='center', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='background_size',
            field=models.CharField(choices=[('cover', 'Cover – stretch to fill the screen'), ('contain', 'Contain – fit whole image inside screen'), ('auto', 'Auto – original image size'), ('50%', '50% – half size'), ('75%', '75% – three-quarter size')], default='cover', max_length=20),
        ),
    ]
