# Generated by Django 6.0.4 on 2026-04-13 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_sitesettings_background_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='background_size',
            field=models.CharField(default='cover', help_text='Any CSS value: cover, contain, auto, 80%, 400px …', max_length=50),
        ),
    ]
