# Generated by Django 6.0.4 on 2026-05-11 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_subject_course_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkpointresponse',
            name='selected_choice',
        ),
        migrations.AlterUniqueTogether(
            name='checkpointresponse',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='checkpointresponse',
            name='checkpoint',
        ),
        migrations.RemoveField(
            model_name='checkpointresponse',
            name='user',
        ),
        migrations.RemoveField(
            model_name='videocheckpoint',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='transcript',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='video_file',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='video_url',
        ),
        migrations.DeleteModel(
            name='CheckpointChoice',
        ),
        migrations.DeleteModel(
            name='CheckpointResponse',
        ),
        migrations.DeleteModel(
            name='VideoCheckpoint',
        ),
    ]
