# Generated by Django 6.0.4 on 2026-05-11 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_remove_checkpointresponse_selected_choice_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
