# Generated by Django 6.0.4 on 2026-06-20 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_pageoverlay'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg', models.CharField(blank=True, max_length=20)),
                ('surface', models.CharField(blank=True, max_length=20)),
                ('surface_2', models.CharField(blank=True, max_length=20)),
                ('border', models.CharField(blank=True, max_length=20)),
                ('text', models.CharField(blank=True, max_length=20)),
                ('accent', models.CharField(blank=True, max_length=20)),
                ('on_accent', models.CharField(blank=True, max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
